// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package productservice

import (
	"context"
	commonpb "seckill-mall/common/common"

	"seckill-mall/common/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolResponse                = commonpb.BoolResponse
	CreateProductRequest        = product.CreateProductRequest
	CreateSeckillProductRequest = product.CreateSeckillProductRequest
	DeductStockRequest          = product.DeductStockRequest
	Empty                       = commonpb.Empty
	GetProductRequest           = product.GetProductRequest
	GetSeckillProductRequest    = product.GetSeckillProductRequest
	IdRequest                   = commonpb.IdRequest
	ListProductsRequest         = product.ListProductsRequest
	ListProductsResponse        = product.ListProductsResponse
	ProductInfo                 = product.ProductInfo
	RollbackStockRequest        = product.RollbackStockRequest
	SeckillProductInfo          = product.SeckillProductInfo
	StockOperationResponse      = product.StockOperationResponse
	UpdateProductRequest        = product.UpdateProductRequest
	UpdateSeckillProductRequest = product.UpdateSeckillProductRequest

	ProductService interface {
		// ============ 商品管理 ============
		CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductInfo, error)
		// 更新商品
		UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*BoolResponse, error)
		// 获取商品详情
		GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductInfo, error)
		// 商品列表
		ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
		// 删除商品
		DeleteProduct(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error)
		// ============ 库存管理 ============
		DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
		// 回滚库存（幂等操作）
		RollbackStock(ctx context.Context, in *RollbackStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
		// 查询库存
		GetStock(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
		// ============ 秒杀商品管理 ============
		CreateSeckillProduct(ctx context.Context, in *CreateSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error)
		// 获取秒杀商品
		GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error)
		// 更新秒杀商品
		UpdateSeckillProduct(ctx context.Context, in *UpdateSeckillProductRequest, opts ...grpc.CallOption) (*BoolResponse, error)
		// 获取进行中的秒杀商品列表
		ListActiveSeckillProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (product.ProductService_ListActiveSeckillProductsClient, error)
	}

	defaultProductService struct {
		cli zrpc.Client
	}
)

func NewProductService(cli zrpc.Client) ProductService {
	return &defaultProductService{
		cli: cli,
	}
}

// ============ 商品管理 ============
func (m *defaultProductService) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductInfo, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

// 更新商品
func (m *defaultProductService) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

// 获取商品详情
func (m *defaultProductService) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductInfo, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// 商品列表
func (m *defaultProductService) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

// 删除商品
func (m *defaultProductService) DeleteProduct(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

// ============ 库存管理 ============
func (m *defaultProductService) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

// 回滚库存（幂等操作）
func (m *defaultProductService) RollbackStock(ctx context.Context, in *RollbackStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.RollbackStock(ctx, in, opts...)
}

// 查询库存
func (m *defaultProductService) GetStock(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}

// ============ 秒杀商品管理 ============
func (m *defaultProductService) CreateSeckillProduct(ctx context.Context, in *CreateSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.CreateSeckillProduct(ctx, in, opts...)
}

// 获取秒杀商品
func (m *defaultProductService) GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.GetSeckillProduct(ctx, in, opts...)
}

// 更新秒杀商品
func (m *defaultProductService) UpdateSeckillProduct(ctx context.Context, in *UpdateSeckillProductRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.UpdateSeckillProduct(ctx, in, opts...)
}

// 获取进行中的秒杀商品列表
func (m *defaultProductService) ListActiveSeckillProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (product.ProductService_ListActiveSeckillProductsClient, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.ListActiveSeckillProducts(ctx, in, opts...)
}
