// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/product.proto

package product

import (
	common "./common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品状态枚举
type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_INACTIVE ProductStatus = 0 // 下架
	ProductStatus_PRODUCT_STATUS_ACTIVE   ProductStatus = 1 // 上架
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_INACTIVE",
		1: "PRODUCT_STATUS_ACTIVE",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_INACTIVE": 0,
		"PRODUCT_STATUS_ACTIVE":   1,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_proto_product_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

// 创建商品请求
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 商品名称 [required, max=200]
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                 // 商品描述 [optional]
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                            // 价格(分) [required, gt=0]
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`                            // 库存数量 [required, gte=0]
	CoverImage    string                 `protobuf:"bytes,5,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"` // 封面图 URL [optional]
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                          // 状态 [optional, default=1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CreateProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 更新商品请求
type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 商品 ID [required]
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 商品名称 [optional]
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                 // 商品描述 [optional]
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                            // 价格(分) [optional]
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`                            // 库存数量 [optional]
	CoverImage    string                 `protobuf:"bytes,6,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"` // 封面图 URL [optional]
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                          // 状态 [optional]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *UpdateProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 商品信息
type ProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`                          // 当前库存
	SoldCount     int64                  `protobuf:"varint,6,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"` // 已售数量
	CoverImage    string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductInfo) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductInfo) GetSoldCount() int64 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *ProductInfo) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *ProductInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProductInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 获取商品详情
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// 商品列表请求（分页）
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    // 搜索关键词 [optional]
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                     // 状态过滤 [optional]
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码 [default=1]
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量 [default=20]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProductsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListProductsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 商品列表响应
type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsResponse) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 扣减库存请求（由 Order-Service 调用）
type DeductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 商品 ID
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // 扣减数量
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`        // 订单号（用于幂等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *DeductStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 回滚库存请求（用于取消订单）
type RollbackStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 商品 ID
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`                    // 回滚数量
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`        // 订单号（用于幂等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackStockRequest) Reset() {
	*x = RollbackStockRequest{}
	mi := &file_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackStockRequest) ProtoMessage() {}

func (x *RollbackStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackStockRequest.ProtoReflect.Descriptor instead.
func (*RollbackStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RollbackStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RollbackStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 库存操作结果
type StockOperationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RemainingStock int64                  `protobuf:"varint,3,opt,name=remaining_stock,json=remainingStock,proto3" json:"remaining_stock,omitempty"` // 剩余库存
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockOperationResponse) Reset() {
	*x = StockOperationResponse{}
	mi := &file_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockOperationResponse) ProtoMessage() {}

func (x *StockOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockOperationResponse.ProtoReflect.Descriptor instead.
func (*StockOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *StockOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StockOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StockOperationResponse) GetRemainingStock() int64 {
	if x != nil {
		return x.RemainingStock
	}
	return 0
}

// 创建秒杀商品请求
type CreateSeckillProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`          // 关联商品 ID
	SeckillPrice  int64                  `protobuf:"varint,2,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"` // 秒杀价格(分)
	SeckillStock  int64                  `protobuf:"varint,3,opt,name=seckill_stock,json=seckillStock,proto3" json:"seckill_stock,omitempty"` // 秒杀库存
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`          // 开始时间戳
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                // 结束时间戳
	PerLimit      int64                  `protobuf:"varint,6,opt,name=per_limit,json=perLimit,proto3" json:"per_limit,omitempty"`             // 每人限购数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillProductRequest) Reset() {
	*x = CreateSeckillProductRequest{}
	mi := &file_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillProductRequest) ProtoMessage() {}

func (x *CreateSeckillProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillProductRequest.ProtoReflect.Descriptor instead.
func (*CreateSeckillProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSeckillProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSeckillProductRequest) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *CreateSeckillProductRequest) GetSeckillStock() int64 {
	if x != nil {
		return x.SeckillStock
	}
	return 0
}

func (x *CreateSeckillProductRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateSeckillProductRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateSeckillProductRequest) GetPerLimit() int64 {
	if x != nil {
		return x.PerLimit
	}
	return 0
}

// 秒杀商品信息
type SeckillProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Product       *ProductInfo           `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"` // 关联商品详情
	SeckillPrice  int64                  `protobuf:"varint,4,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	SeckillStock  int64                  `protobuf:"varint,5,opt,name=seckill_stock,json=seckillStock,proto3" json:"seckill_stock,omitempty"`
	SoldCount     int64                  `protobuf:"varint,6,opt,name=sold_count,json=soldCount,proto3" json:"sold_count,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PerLimit      int64                  `protobuf:"varint,9,opt,name=per_limit,json=perLimit,proto3" json:"per_limit,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"` // 0=未开始, 1=进行中, 2=已结束
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillProductInfo) Reset() {
	*x = SeckillProductInfo{}
	mi := &file_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillProductInfo) ProtoMessage() {}

func (x *SeckillProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillProductInfo.ProtoReflect.Descriptor instead.
func (*SeckillProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *SeckillProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeckillProductInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillProductInfo) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *SeckillProductInfo) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *SeckillProductInfo) GetSeckillStock() int64 {
	if x != nil {
		return x.SeckillStock
	}
	return 0
}

func (x *SeckillProductInfo) GetSoldCount() int64 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *SeckillProductInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SeckillProductInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SeckillProductInfo) GetPerLimit() int64 {
	if x != nil {
		return x.PerLimit
	}
	return 0
}

func (x *SeckillProductInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SeckillProductInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 获取秒杀商品详情
type GetSeckillProductRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeckillProductId int64                  `protobuf:"varint,1,opt,name=seckill_product_id,json=seckillProductId,proto3" json:"seckill_product_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSeckillProductRequest) Reset() {
	*x = GetSeckillProductRequest{}
	mi := &file_proto_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeckillProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeckillProductRequest) ProtoMessage() {}

func (x *GetSeckillProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeckillProductRequest.ProtoReflect.Descriptor instead.
func (*GetSeckillProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{11}
}

func (x *GetSeckillProductRequest) GetSeckillProductId() int64 {
	if x != nil {
		return x.SeckillProductId
	}
	return 0
}

// 更新秒杀商品
type UpdateSeckillProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SeckillPrice  int64                  `protobuf:"varint,2,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	SeckillStock  int64                  `protobuf:"varint,3,opt,name=seckill_stock,json=seckillStock,proto3" json:"seckill_stock,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PerLimit      int64                  `protobuf:"varint,6,opt,name=per_limit,json=perLimit,proto3" json:"per_limit,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeckillProductRequest) Reset() {
	*x = UpdateSeckillProductRequest{}
	mi := &file_proto_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeckillProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeckillProductRequest) ProtoMessage() {}

func (x *UpdateSeckillProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeckillProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeckillProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSeckillProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetSeckillStock() int64 {
	if x != nil {
		return x.SeckillStock
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetPerLimit() int64 {
	if x != nil {
		return x.PerLimit
	}
	return 0
}

func (x *UpdateSeckillProductRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\aproduct\x1a\x12proto/common.proto\"\xb1\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\x12\x1f\n" +
	"\vcover_image\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\xc1\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x1f\n" +
	"\vcover_image\x18\x06 \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\x95\x02\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x06 \x01(\x03R\tsoldCount\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"x\n" +
	"\x13ListProductsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x8f\x01\n" +
	"\x14ListProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.product.ProductInfoR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"j\n" +
	"\x12DeductStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"l\n" +
	"\x14RollbackStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"u\n" +
	"\x16StockOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fremaining_stock\x18\x03 \x01(\x03R\x0eremainingStock\"\xdd\x01\n" +
	"\x1bCreateSeckillProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12#\n" +
	"\rseckill_price\x18\x02 \x01(\x03R\fseckillPrice\x12#\n" +
	"\rseckill_stock\x18\x03 \x01(\x03R\fseckillStock\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1b\n" +
	"\tper_limit\x18\x06 \x01(\x03R\bperLimit\"\xea\x02\n" +
	"\x12SeckillProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12.\n" +
	"\aproduct\x18\x03 \x01(\v2\x14.product.ProductInfoR\aproduct\x12#\n" +
	"\rseckill_price\x18\x04 \x01(\x03R\fseckillPrice\x12#\n" +
	"\rseckill_stock\x18\x05 \x01(\x03R\fseckillStock\x12\x1d\n" +
	"\n" +
	"sold_count\x18\x06 \x01(\x03R\tsoldCount\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x12\x1b\n" +
	"\tper_limit\x18\t \x01(\x03R\bperLimit\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"H\n" +
	"\x18GetSeckillProductRequest\x12,\n" +
	"\x12seckill_product_id\x18\x01 \x01(\x03R\x10seckillProductId\"\xe6\x01\n" +
	"\x1bUpdateSeckillProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rseckill_price\x18\x02 \x01(\x03R\fseckillPrice\x12#\n" +
	"\rseckill_stock\x18\x03 \x01(\x03R\fseckillStock\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1b\n" +
	"\tper_limit\x18\x06 \x01(\x03R\bperLimit\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status*G\n" +
	"\rProductStatus\x12\x1b\n" +
	"\x17PRODUCT_STATUS_INACTIVE\x10\x00\x12\x19\n" +
	"\x15PRODUCT_STATUS_ACTIVE\x10\x012\x90\a\n" +
	"\x0eProductService\x12D\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x14.product.ProductInfo\x12D\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x14.common.BoolResponse\x12>\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x14.product.ProductInfo\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x128\n" +
	"\rDeleteProduct\x12\x11.common.IdRequest\x1a\x14.common.BoolResponse\x12K\n" +
	"\vDeductStock\x12\x1b.product.DeductStockRequest\x1a\x1f.product.StockOperationResponse\x12O\n" +
	"\rRollbackStock\x12\x1d.product.RollbackStockRequest\x1a\x1f.product.StockOperationResponse\x12>\n" +
	"\bGetStock\x12\x11.common.IdRequest\x1a\x1f.product.StockOperationResponse\x12Y\n" +
	"\x14CreateSeckillProduct\x12$.product.CreateSeckillProductRequest\x1a\x1b.product.SeckillProductInfo\x12S\n" +
	"\x11GetSeckillProduct\x12!.product.GetSeckillProductRequest\x1a\x1b.product.SeckillProductInfo\x12R\n" +
	"\x14UpdateSeckillProduct\x12$.product.UpdateSeckillProductRequest\x1a\x14.common.BoolResponse\x12I\n" +
	"\x19ListActiveSeckillProducts\x12\r.common.Empty\x1a\x1b.product.SeckillProductInfo0\x01B\vZ\t./productb\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_product_proto_goTypes = []any{
	(ProductStatus)(0),                  // 0: product.ProductStatus
	(*CreateProductRequest)(nil),        // 1: product.CreateProductRequest
	(*UpdateProductRequest)(nil),        // 2: product.UpdateProductRequest
	(*ProductInfo)(nil),                 // 3: product.ProductInfo
	(*GetProductRequest)(nil),           // 4: product.GetProductRequest
	(*ListProductsRequest)(nil),         // 5: product.ListProductsRequest
	(*ListProductsResponse)(nil),        // 6: product.ListProductsResponse
	(*DeductStockRequest)(nil),          // 7: product.DeductStockRequest
	(*RollbackStockRequest)(nil),        // 8: product.RollbackStockRequest
	(*StockOperationResponse)(nil),      // 9: product.StockOperationResponse
	(*CreateSeckillProductRequest)(nil), // 10: product.CreateSeckillProductRequest
	(*SeckillProductInfo)(nil),          // 11: product.SeckillProductInfo
	(*GetSeckillProductRequest)(nil),    // 12: product.GetSeckillProductRequest
	(*UpdateSeckillProductRequest)(nil), // 13: product.UpdateSeckillProductRequest
	(*common.IdRequest)(nil),            // 14: common.IdRequest
	(*common.Empty)(nil),                // 15: common.Empty
	(*common.BoolResponse)(nil),         // 16: common.BoolResponse
}
var file_proto_product_proto_depIdxs = []int32{
	3,  // 0: product.ListProductsResponse.products:type_name -> product.ProductInfo
	3,  // 1: product.SeckillProductInfo.product:type_name -> product.ProductInfo
	1,  // 2: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	2,  // 3: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	4,  // 4: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	5,  // 5: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	14, // 6: product.ProductService.DeleteProduct:input_type -> common.IdRequest
	7,  // 7: product.ProductService.DeductStock:input_type -> product.DeductStockRequest
	8,  // 8: product.ProductService.RollbackStock:input_type -> product.RollbackStockRequest
	14, // 9: product.ProductService.GetStock:input_type -> common.IdRequest
	10, // 10: product.ProductService.CreateSeckillProduct:input_type -> product.CreateSeckillProductRequest
	12, // 11: product.ProductService.GetSeckillProduct:input_type -> product.GetSeckillProductRequest
	13, // 12: product.ProductService.UpdateSeckillProduct:input_type -> product.UpdateSeckillProductRequest
	15, // 13: product.ProductService.ListActiveSeckillProducts:input_type -> common.Empty
	3,  // 14: product.ProductService.CreateProduct:output_type -> product.ProductInfo
	16, // 15: product.ProductService.UpdateProduct:output_type -> common.BoolResponse
	3,  // 16: product.ProductService.GetProduct:output_type -> product.ProductInfo
	6,  // 17: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	16, // 18: product.ProductService.DeleteProduct:output_type -> common.BoolResponse
	9,  // 19: product.ProductService.DeductStock:output_type -> product.StockOperationResponse
	9,  // 20: product.ProductService.RollbackStock:output_type -> product.StockOperationResponse
	9,  // 21: product.ProductService.GetStock:output_type -> product.StockOperationResponse
	11, // 22: product.ProductService.CreateSeckillProduct:output_type -> product.SeckillProductInfo
	11, // 23: product.ProductService.GetSeckillProduct:output_type -> product.SeckillProductInfo
	16, // 24: product.ProductService.UpdateSeckillProduct:output_type -> common.BoolResponse
	11, // 25: product.ProductService.ListActiveSeckillProducts:output_type -> product.SeckillProductInfo
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		EnumInfos:         file_proto_product_proto_enumTypes,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
