// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/product.proto

package product

import (
	common "./common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_CreateProduct_FullMethodName             = "/product.ProductService/CreateProduct"
	ProductService_UpdateProduct_FullMethodName             = "/product.ProductService/UpdateProduct"
	ProductService_GetProduct_FullMethodName                = "/product.ProductService/GetProduct"
	ProductService_ListProducts_FullMethodName              = "/product.ProductService/ListProducts"
	ProductService_DeleteProduct_FullMethodName             = "/product.ProductService/DeleteProduct"
	ProductService_DeductStock_FullMethodName               = "/product.ProductService/DeductStock"
	ProductService_RollbackStock_FullMethodName             = "/product.ProductService/RollbackStock"
	ProductService_GetStock_FullMethodName                  = "/product.ProductService/GetStock"
	ProductService_CreateSeckillProduct_FullMethodName      = "/product.ProductService/CreateSeckillProduct"
	ProductService_GetSeckillProduct_FullMethodName         = "/product.ProductService/GetSeckillProduct"
	ProductService_UpdateSeckillProduct_FullMethodName      = "/product.ProductService/UpdateSeckillProduct"
	ProductService_ListActiveSeckillProducts_FullMethodName = "/product.ProductService/ListActiveSeckillProducts"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 商品与库存服务
type ProductServiceClient interface {
	// ============ 商品管理 ============
	// 创建商品
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductInfo, error)
	// 更新商品
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error)
	// 获取商品详情
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductInfo, error)
	// 商品列表
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// 删除商品
	DeleteProduct(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BoolResponse, error)
	// ============ 库存管理 ============
	// 扣减库存（幂等操作）
	DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
	// 回滚库存（幂等操作）
	RollbackStock(ctx context.Context, in *RollbackStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
	// 查询库存
	GetStock(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*StockOperationResponse, error)
	// ============ 秒杀商品管理 ============
	// 创建秒杀商品
	CreateSeckillProduct(ctx context.Context, in *CreateSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error)
	// 获取秒杀商品
	GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error)
	// 更新秒杀商品
	UpdateSeckillProduct(ctx context.Context, in *UpdateSeckillProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error)
	// 获取进行中的秒杀商品列表
	ListActiveSeckillProducts(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SeckillProductInfo], error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductInfo)
	err := c.cc.Invoke(ctx, ProductService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BoolResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductInfo)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BoolResponse)
	err := c.cc.Invoke(ctx, ProductService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockOperationResponse)
	err := c.cc.Invoke(ctx, ProductService_DeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) RollbackStock(ctx context.Context, in *RollbackStockRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockOperationResponse)
	err := c.cc.Invoke(ctx, ProductService_RollbackStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetStock(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*StockOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockOperationResponse)
	err := c.cc.Invoke(ctx, ProductService_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateSeckillProduct(ctx context.Context, in *CreateSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillProductInfo)
	err := c.cc.Invoke(ctx, ProductService_CreateSeckillProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillProductInfo)
	err := c.cc.Invoke(ctx, ProductService_GetSeckillProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateSeckillProduct(ctx context.Context, in *UpdateSeckillProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BoolResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateSeckillProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListActiveSeckillProducts(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SeckillProductInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], ProductService_ListActiveSeckillProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.Empty, SeckillProductInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_ListActiveSeckillProductsClient = grpc.ServerStreamingClient[SeckillProductInfo]

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// 商品与库存服务
type ProductServiceServer interface {
	// ============ 商品管理 ============
	// 创建商品
	CreateProduct(context.Context, *CreateProductRequest) (*ProductInfo, error)
	// 更新商品
	UpdateProduct(context.Context, *UpdateProductRequest) (*common.BoolResponse, error)
	// 获取商品详情
	GetProduct(context.Context, *GetProductRequest) (*ProductInfo, error)
	// 商品列表
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// 删除商品
	DeleteProduct(context.Context, *common.IdRequest) (*common.BoolResponse, error)
	// ============ 库存管理 ============
	// 扣减库存（幂等操作）
	DeductStock(context.Context, *DeductStockRequest) (*StockOperationResponse, error)
	// 回滚库存（幂等操作）
	RollbackStock(context.Context, *RollbackStockRequest) (*StockOperationResponse, error)
	// 查询库存
	GetStock(context.Context, *common.IdRequest) (*StockOperationResponse, error)
	// ============ 秒杀商品管理 ============
	// 创建秒杀商品
	CreateSeckillProduct(context.Context, *CreateSeckillProductRequest) (*SeckillProductInfo, error)
	// 获取秒杀商品
	GetSeckillProduct(context.Context, *GetSeckillProductRequest) (*SeckillProductInfo, error)
	// 更新秒杀商品
	UpdateSeckillProduct(context.Context, *UpdateSeckillProductRequest) (*common.BoolResponse, error)
	// 获取进行中的秒杀商品列表
	ListActiveSeckillProducts(*common.Empty, grpc.ServerStreamingServer[SeckillProductInfo]) error
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*ProductInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*common.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*ProductInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductServiceServer) DeleteProduct(context.Context, *common.IdRequest) (*common.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductServiceServer) DeductStock(context.Context, *DeductStockRequest) (*StockOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedProductServiceServer) RollbackStock(context.Context, *RollbackStockRequest) (*StockOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackStock not implemented")
}
func (UnimplementedProductServiceServer) GetStock(context.Context, *common.IdRequest) (*StockOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedProductServiceServer) CreateSeckillProduct(context.Context, *CreateSeckillProductRequest) (*SeckillProductInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeckillProduct not implemented")
}
func (UnimplementedProductServiceServer) GetSeckillProduct(context.Context, *GetSeckillProductRequest) (*SeckillProductInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateSeckillProduct(context.Context, *UpdateSeckillProductRequest) (*common.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSeckillProduct not implemented")
}
func (UnimplementedProductServiceServer) ListActiveSeckillProducts(*common.Empty, grpc.ServerStreamingServer[SeckillProductInfo]) error {
	return status.Error(codes.Unimplemented, "method ListActiveSeckillProducts not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeductStock(ctx, req.(*DeductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_RollbackStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).RollbackStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_RollbackStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).RollbackStock(ctx, req.(*RollbackStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetStock(ctx, req.(*common.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateSeckillProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeckillProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateSeckillProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateSeckillProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateSeckillProduct(ctx, req.(*CreateSeckillProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetSeckillProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetSeckillProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetSeckillProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetSeckillProduct(ctx, req.(*GetSeckillProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateSeckillProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSeckillProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateSeckillProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateSeckillProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateSeckillProduct(ctx, req.(*UpdateSeckillProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListActiveSeckillProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).ListActiveSeckillProducts(m, &grpc.GenericServerStream[common.Empty, SeckillProductInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProductService_ListActiveSeckillProductsServer = grpc.ServerStreamingServer[SeckillProductInfo]

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductService_ListProducts_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "DeductStock",
			Handler:    _ProductService_DeductStock_Handler,
		},
		{
			MethodName: "RollbackStock",
			Handler:    _ProductService_RollbackStock_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _ProductService_GetStock_Handler,
		},
		{
			MethodName: "CreateSeckillProduct",
			Handler:    _ProductService_CreateSeckillProduct_Handler,
		},
		{
			MethodName: "GetSeckillProduct",
			Handler:    _ProductService_GetSeckillProduct_Handler,
		},
		{
			MethodName: "UpdateSeckillProduct",
			Handler:    _ProductService_UpdateSeckillProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListActiveSeckillProducts",
			Handler:       _ProductService_ListActiveSeckillProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/product.proto",
}
