// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"
	commonpb "seckill-mall/common/common"

	"seckill-mall/common/product"
	"seckill-mall/product-service/internal/logic"
	"seckill-mall/product-service/internal/svc"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

// ============ 商品管理 ============
func (s *ProductServiceServer) CreateProduct(ctx context.Context, in *product.CreateProductRequest) (*product.ProductInfo, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

// 更新商品
func (s *ProductServiceServer) UpdateProduct(ctx context.Context, in *product.UpdateProductRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// 获取商品详情
func (s *ProductServiceServer) GetProduct(ctx context.Context, in *product.GetProductRequest) (*product.ProductInfo, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// 商品列表
func (s *ProductServiceServer) ListProducts(ctx context.Context, in *product.ListProductsRequest) (*product.ListProductsResponse, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

// 删除商品
func (s *ProductServiceServer) DeleteProduct(ctx context.Context, in *commonpb.IdRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

// ============ 库存管理 ============
func (s *ProductServiceServer) DeductStock(ctx context.Context, in *product.DeductStockRequest) (*product.StockOperationResponse, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// 回滚库存（幂等操作）
func (s *ProductServiceServer) RollbackStock(ctx context.Context, in *product.RollbackStockRequest) (*product.StockOperationResponse, error) {
	l := logic.NewRollbackStockLogic(ctx, s.svcCtx)
	return l.RollbackStock(in)
}

// 查询库存
func (s *ProductServiceServer) GetStock(ctx context.Context, in *commonpb.IdRequest) (*product.StockOperationResponse, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

// ============ 秒杀商品管理 ============
func (s *ProductServiceServer) CreateSeckillProduct(ctx context.Context, in *product.CreateSeckillProductRequest) (*product.SeckillProductInfo, error) {
	l := logic.NewCreateSeckillProductLogic(ctx, s.svcCtx)
	return l.CreateSeckillProduct(in)
}

// 获取秒杀商品
func (s *ProductServiceServer) GetSeckillProduct(ctx context.Context, in *product.GetSeckillProductRequest) (*product.SeckillProductInfo, error) {
	l := logic.NewGetSeckillProductLogic(ctx, s.svcCtx)
	return l.GetSeckillProduct(in)
}

// 更新秒杀商品
func (s *ProductServiceServer) UpdateSeckillProduct(ctx context.Context, in *product.UpdateSeckillProductRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewUpdateSeckillProductLogic(ctx, s.svcCtx)
	return l.UpdateSeckillProduct(in)
}

// 获取进行中的秒杀商品列表
func (s *ProductServiceServer) ListActiveSeckillProducts(in *commonpb.Empty, stream product.ProductService_ListActiveSeckillProductsServer) error {
	l := logic.NewListActiveSeckillProductsLogic(stream.Context(), s.svcCtx)
	return l.ListActiveSeckillProducts(in, stream)
}
