// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package seckillservice

import (
	"context"

	"seckill-mall/common/seckill"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SeckillRequest        = seckill.SeckillRequest
	SeckillResponse       = seckill.SeckillResponse
	SeckillResultRequest  = seckill.SeckillResultRequest
	SeckillResultResponse = seckill.SeckillResultResponse
	SeckillStatusRequest  = seckill.SeckillStatusRequest
	SeckillStatusResponse = seckill.SeckillStatusResponse

	SeckillService interface {
		// 秒杀下单（核心接口）
		Seckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error)
		// 查询秒杀状态（轮询接口）
		GetSeckillStatus(ctx context.Context, in *SeckillStatusRequest, opts ...grpc.CallOption) (*SeckillStatusResponse, error)
		// 查询秒杀结果
		GetSeckillResult(ctx context.Context, in *SeckillResultRequest, opts ...grpc.CallOption) (*SeckillResultResponse, error)
	}

	defaultSeckillService struct {
		cli zrpc.Client
	}
)

func NewSeckillService(cli zrpc.Client) SeckillService {
	return &defaultSeckillService{
		cli: cli,
	}
}

// 秒杀下单（核心接口）
func (m *defaultSeckillService) Seckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error) {
	client := seckill.NewSeckillServiceClient(m.cli.Conn())
	return client.Seckill(ctx, in, opts...)
}

// 查询秒杀状态（轮询接口）
func (m *defaultSeckillService) GetSeckillStatus(ctx context.Context, in *SeckillStatusRequest, opts ...grpc.CallOption) (*SeckillStatusResponse, error) {
	client := seckill.NewSeckillServiceClient(m.cli.Conn())
	return client.GetSeckillStatus(ctx, in, opts...)
}

// 查询秒杀结果
func (m *defaultSeckillService) GetSeckillResult(ctx context.Context, in *SeckillResultRequest, opts ...grpc.CallOption) (*SeckillResultResponse, error) {
	client := seckill.NewSeckillServiceClient(m.cli.Conn())
	return client.GetSeckillResult(ctx, in, opts...)
}
