global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['host.docker.internal:9180']

  - job_name: seckill-service
    static_configs:
      - targets: ['host.docker.internal:9181']

  - job_name: order-service
    static_configs:
      - targets: ['host.docker.internal:9182']

  - job_name: product-service
    static_configs:
      - targets: ['host.docker.internal:9183']

  - job_name: user-service
    static_configs:
      - targets: ['host.docker.internal:9184']
