// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderservice

import (
	"context"

	"seckill-mall/order-service/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolResponse             = order.BoolResponse
	CancelOrderRequest       = order.CancelOrderRequest
	CreateNormalOrderRequest = order.CreateNormalOrderRequest
	GetOrderRequest          = order.GetOrderRequest
	ListUserOrdersRequest    = order.ListUserOrdersRequest
	ListUserOrdersResponse   = order.ListUserOrdersResponse
	OrderInfo                = order.OrderInfo
	PayOrderRequest          = order.PayOrderRequest
	RefundOrderRequest       = order.RefundOrderRequest
	SeckillOrderMessage      = order.SeckillOrderMessage

	OrderService interface {
		// ============ gRPC 接口 ============
		CreateNormalOrder(ctx context.Context, in *CreateNormalOrderRequest, opts ...grpc.CallOption) (*OrderInfo, error)
		// 获取订单详情
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderInfo, error)
		// 用户订单列表
		ListUserOrders(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error)
		// 取消订单
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error)
		// 支付订单
		PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error)
		// 退款
		RefundOrder(ctx context.Context, in *RefundOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// ============ gRPC 接口 ============
func (m *defaultOrderService) CreateNormalOrder(ctx context.Context, in *CreateNormalOrderRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateNormalOrder(ctx, in, opts...)
}

// 获取订单详情
func (m *defaultOrderService) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

// 用户订单列表
func (m *defaultOrderService) ListUserOrders(ctx context.Context, in *ListUserOrdersRequest, opts ...grpc.CallOption) (*ListUserOrdersResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.ListUserOrders(ctx, in, opts...)
}

// 取消订单
func (m *defaultOrderService) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// 支付订单
func (m *defaultOrderService) PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.PayOrder(ctx, in, opts...)
}

// 退款
func (m *defaultOrderService) RefundOrder(ctx context.Context, in *RefundOrderRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.RefundOrder(ctx, in, opts...)
}
