// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: seckill.proto

package seckill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 秒杀请求
type SeckillRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 // 用户 ID [required]
	SeckillProductId int64                  `protobuf:"varint,2,opt,name=seckill_product_id,json=seckillProductId,proto3" json:"seckill_product_id,omitempty"` // 秒杀商品 ID [required]
	Quantity         int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                           // 购买数量 [required, default=1]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeckillRequest) Reset() {
	*x = SeckillRequest{}
	mi := &file_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillRequest) ProtoMessage() {}

func (x *SeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillRequest.ProtoReflect.Descriptor instead.
func (*SeckillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillRequest) GetSeckillProductId() int64 {
	if x != nil {
		return x.SeckillProductId
	}
	return 0
}

func (x *SeckillRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 秒杀结果（同步返回）
type SeckillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                      // 结果码: SUCCESS, SOLD_OUT, ALREADY_PURCHASED, SECKILL_NOT_STARTED, SECKILL_ENDED
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                // 结果描述
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号（仅成功时返回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	mi := &file_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeckillResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SeckillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SeckillResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 秒杀状态查询
type SeckillStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SeckillProductId int64                  `protobuf:"varint,2,opt,name=seckill_product_id,json=seckillProductId,proto3" json:"seckill_product_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeckillStatusRequest) Reset() {
	*x = SeckillStatusRequest{}
	mi := &file_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillStatusRequest) ProtoMessage() {}

func (x *SeckillStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillStatusRequest.ProtoReflect.Descriptor instead.
func (*SeckillStatusRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *SeckillStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SeckillStatusRequest) GetSeckillProductId() int64 {
	if x != nil {
		return x.SeckillProductId
	}
	return 0
}

type SeckillStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                  // pending=排队中, success=成功, failed=失败
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillStatusResponse) Reset() {
	*x = SeckillStatusResponse{}
	mi := &file_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillStatusResponse) ProtoMessage() {}

func (x *SeckillStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillStatusResponse.ProtoReflect.Descriptor instead.
func (*SeckillStatusResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *SeckillStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeckillStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SeckillStatusResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillStatusResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 秒杀结果查询
type SeckillResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号 [required]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResultRequest) Reset() {
	*x = SeckillResultRequest{}
	mi := &file_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResultRequest) ProtoMessage() {}

func (x *SeckillResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResultRequest.ProtoReflect.Descriptor instead.
func (*SeckillResultRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *SeckillResultRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SeckillResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"` // 实付金额(分)
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`  // order_status=订单状态
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResultResponse) Reset() {
	*x = SeckillResultResponse{}
	mi := &file_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResultResponse) ProtoMessage() {}

func (x *SeckillResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResultResponse.ProtoReflect.Descriptor instead.
func (*SeckillResultResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *SeckillResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SeckillResultResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SeckillResultResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillResultResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SeckillResultResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SeckillResultResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SeckillResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeckillResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 更新秒杀订单状态（Order-Service 处理完成后回调，将 Redis 订单状态从 pending → success）
type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单号 [required]
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                  // 新状态 [required]: "success" | "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_seckill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_seckill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOrderStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_seckill_proto protoreflect.FileDescriptor

const file_seckill_proto_rawDesc = "" +
	"\n" +
	"\rseckill.proto\x12\aseckill\"s\n" +
	"\x0eSeckillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12,\n" +
	"\x12seckill_product_id\x18\x02 \x01(\x03R\x10seckillProductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"t\n" +
	"\x0fSeckillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\"]\n" +
	"\x14SeckillStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12,\n" +
	"\x12seckill_product_id\x18\x02 \x01(\x03R\x10seckillProductId\"\x85\x01\n" +
	"\x15SeckillStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"1\n" +
	"\x14SeckillResultRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xf4\x01\n" +
	"\x15SeckillResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"M\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x19UpdateOrderStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd0\x02\n" +
	"\x0eSeckillService\x12<\n" +
	"\aSeckill\x12\x17.seckill.SeckillRequest\x1a\x18.seckill.SeckillResponse\x12Q\n" +
	"\x10GetSeckillStatus\x12\x1d.seckill.SeckillStatusRequest\x1a\x1e.seckill.SeckillStatusResponse\x12Q\n" +
	"\x10GetSeckillResult\x12\x1d.seckill.SeckillResultRequest\x1a\x1e.seckill.SeckillResultResponse\x12Z\n" +
	"\x11UpdateOrderStatus\x12!.seckill.UpdateOrderStatusRequest\x1a\".seckill.UpdateOrderStatusResponseB\vZ\t./seckillb\x06proto3"

var (
	file_seckill_proto_rawDescOnce sync.Once
	file_seckill_proto_rawDescData []byte
)

func file_seckill_proto_rawDescGZIP() []byte {
	file_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)))
	})
	return file_seckill_proto_rawDescData
}

var file_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_seckill_proto_goTypes = []any{
	(*SeckillRequest)(nil),            // 0: seckill.SeckillRequest
	(*SeckillResponse)(nil),           // 1: seckill.SeckillResponse
	(*SeckillStatusRequest)(nil),      // 2: seckill.SeckillStatusRequest
	(*SeckillStatusResponse)(nil),     // 3: seckill.SeckillStatusResponse
	(*SeckillResultRequest)(nil),      // 4: seckill.SeckillResultRequest
	(*SeckillResultResponse)(nil),     // 5: seckill.SeckillResultResponse
	(*UpdateOrderStatusRequest)(nil),  // 6: seckill.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil), // 7: seckill.UpdateOrderStatusResponse
}
var file_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillService.Seckill:input_type -> seckill.SeckillRequest
	2, // 1: seckill.SeckillService.GetSeckillStatus:input_type -> seckill.SeckillStatusRequest
	4, // 2: seckill.SeckillService.GetSeckillResult:input_type -> seckill.SeckillResultRequest
	6, // 3: seckill.SeckillService.UpdateOrderStatus:input_type -> seckill.UpdateOrderStatusRequest
	1, // 4: seckill.SeckillService.Seckill:output_type -> seckill.SeckillResponse
	3, // 5: seckill.SeckillService.GetSeckillStatus:output_type -> seckill.SeckillStatusResponse
	5, // 6: seckill.SeckillService.GetSeckillResult:output_type -> seckill.SeckillResultResponse
	7, // 7: seckill.SeckillService.UpdateOrderStatus:output_type -> seckill.UpdateOrderStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckill_proto_init() }
func file_seckill_proto_init() {
	if File_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_proto_msgTypes,
	}.Build()
	File_seckill_proto = out.File
	file_seckill_proto_goTypes = nil
	file_seckill_proto_depIdxs = nil
}
