// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package server

import (
	"context"

	"seckill-mall/seckill-service/internal/logic"
	"seckill-mall/seckill-service/internal/svc"
	"seckill-mall/seckill-service/seckill"
)

type SeckillServiceServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSeckillServiceServer
}

func NewSeckillServiceServer(svcCtx *svc.ServiceContext) *SeckillServiceServer {
	return &SeckillServiceServer{
		svcCtx: svcCtx,
	}
}

// 秒杀下单（核心接口）
func (s *SeckillServiceServer) Seckill(ctx context.Context, in *seckill.SeckillRequest) (*seckill.SeckillResponse, error) {
	l := logic.NewSeckillLogic(ctx, s.svcCtx)
	return l.Seckill(in)
}

// 查询秒杀状态（轮询接口）
func (s *SeckillServiceServer) GetSeckillStatus(ctx context.Context, in *seckill.SeckillStatusRequest) (*seckill.SeckillStatusResponse, error) {
	l := logic.NewGetSeckillStatusLogic(ctx, s.svcCtx)
	return l.GetSeckillStatus(in)
}

// 查询秒杀结果
func (s *SeckillServiceServer) GetSeckillResult(ctx context.Context, in *seckill.SeckillResultRequest) (*seckill.SeckillResultResponse, error) {
	l := logic.NewGetSeckillResultLogic(ctx, s.svcCtx)
	return l.GetSeckillResult(in)
}
