// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package server

import (
	"context"

	commonpb "seckill-mall/common/common"
	"seckill-mall/common/seckill"
	"seckill-mall/seckill-service/internal/logic"
	"seckill-mall/seckill-service/internal/model"
	"seckill-mall/seckill-service/internal/model/entity"
	"seckill-mall/seckill-service/internal/svc"
)

type SeckillServiceServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSeckillServiceServer
}

func NewSeckillServiceServer(svcCtx *svc.ServiceContext) *SeckillServiceServer {
	return &SeckillServiceServer{
		svcCtx: svcCtx,
	}
}

// 秒杀下单（核心接口）
func (s *SeckillServiceServer) Seckill(ctx context.Context, in *seckill.SeckillRequest) (*seckill.SeckillResponse, error) {
	l := logic.NewSeckillLogic(ctx, s.svcCtx)
	return l.Seckill(in)
}

// 查询秒杀状态（轮询接口）
func (s *SeckillServiceServer) GetSeckillStatus(ctx context.Context, in *seckill.SeckillStatusRequest) (*seckill.SeckillStatusResponse, error) {
	l := logic.NewGetSeckillStatusLogic(ctx, s.svcCtx)
	return l.GetSeckillStatus(in)
}

// 查询秒杀结果
func (s *SeckillServiceServer) GetSeckillResult(ctx context.Context, in *seckill.SeckillResultRequest) (*seckill.SeckillResultResponse, error) {
	l := logic.NewGetSeckillResultLogic(ctx, s.svcCtx)
	return l.GetSeckillResult(in)
}

// 更新订单状态（Order-Service 内部调用，将 pending → success）
func (s *SeckillServiceServer) UpdateOrderStatus(ctx context.Context, in *seckill.UpdateOrderStatusRequest) (*seckill.UpdateOrderStatusResponse, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

// 超时失败补偿（Order-Service 内部调用）
func (s *SeckillServiceServer) CompensateFailedOrder(ctx context.Context, in *seckill.CompensateFailedOrderRequest) (*seckill.CompensateFailedOrderResponse, error) {
	l := logic.NewCompensateFailedOrderLogic(ctx, s.svcCtx)
	return l.CompensateFailedOrder(in)
}

// 查询预占信息
func (s *SeckillServiceServer) GetReservation(ctx context.Context, in *seckill.GetReservationRequest) (*seckill.ReservationInfo, error) {
	if s.svcCtx.ReservationLedger == nil {
		return &seckill.ReservationInfo{
			ReservationId: in.ReservationId,
			OrderId:       in.OrderId,
		}, nil
	}
	reservation, err := s.svcCtx.ReservationLedger.GetReservation(ctx, in.ReservationId, in.OrderId)
	if err != nil {
		if err == model.ErrNotFound {
			return &seckill.ReservationInfo{
				ReservationId: in.ReservationId,
				OrderId:       in.OrderId,
			}, nil
		}
		return nil, err
	}
	return reservationToProto(reservation), nil
}

// 释放预占
func (s *SeckillServiceServer) ReleaseReservation(ctx context.Context, in *seckill.ReleaseReservationRequest) (*seckill.ReleaseReservationResponse, error) {
	if s.svcCtx.ReservationLedger == nil {
		return &seckill.ReleaseReservationResponse{
			Success: false,
			Message: "reservation ledger 未初始化",
		}, nil
	}
	reservation, err := s.svcCtx.ReservationLedger.ReleaseReservation(ctx, &model.ReleaseReservationInput{
		ReservationID: in.ReservationId,
		OrderID:       in.OrderId,
		Reason:        in.Reason,
		TargetStatus:  entity.ReservationStatusReleased,
		Operator:      "system",
	})
	if err != nil {
		if err == model.ErrNotFound {
			return &seckill.ReleaseReservationResponse{
				Success: false,
				Message: "预占不存在",
			}, nil
		}
		return nil, err
	}
	return &seckill.ReleaseReservationResponse{
		Success: true,
		Message: "预占释放成功",
		Reservation: reservationToProto(reservation),
	}, nil
}

func (s *SeckillServiceServer) AdvanceReservation(ctx context.Context, in *seckill.AdvanceReservationRequest) (*seckill.AdvanceReservationResponse, error) {
	if s.svcCtx.ReservationLedger == nil {
		return &seckill.AdvanceReservationResponse{
			Success: false,
			Message: "reservation ledger 未初始化",
		}, nil
	}

	reservation, err := s.svcCtx.ReservationLedger.AdvanceReservation(ctx, &model.AdvanceReservationInput{
		ReservationID: in.GetReservationId(),
		OrderID:       in.GetOrderId(),
		TargetStatus:  fromProtoReservationStatus(in.GetTargetStatus()),
		Reason:        in.GetReason(),
		Operator:      in.GetOperator(),
		PaymentID:     in.GetPaymentId(),
		AllowRecover:  in.GetAllowRecover(),
	})
	if err != nil {
		if err == model.ErrNotFound {
			return &seckill.AdvanceReservationResponse{
				Success: false,
				Message: "预占不存在",
			}, nil
		}
		if err == model.ErrInvalidParams {
			return &seckill.AdvanceReservationResponse{
				Success: false,
				Message: "预占状态推进非法",
			}, nil
		}
		return nil, err
	}

	return &seckill.AdvanceReservationResponse{
		Success:     true,
		Message:     "预占推进成功",
		Reservation: reservationToProto(reservation),
	}, nil
}

func reservationToProto(reservation *entity.SeckillReservation) *seckill.ReservationInfo {
	if reservation == nil {
		return &seckill.ReservationInfo{}
	}
	return &seckill.ReservationInfo{
		ReservationId: reservation.ReservationId,
		OrderId:       reservation.OrderId,
		UserId:        reservation.UserId,
		SeckillProductId: reservation.SeckillProductId,
		ProductId:     reservation.ProductId,
		Quantity:      int64(reservation.Quantity),
		Amount:        reservation.Amount,
		Status:        toProtoReservationStatus(reservation.Status),
		Reason:        reservation.Reason,
		ExpireAt:      reservation.ExpireAt,
		CreatedAt:     reservation.CreatedAt,
		UpdatedAt:     reservation.UpdatedAt,
	}
}

func toProtoReservationStatus(status int32) commonpb.ReservationStatus {
	switch status {
	case entity.ReservationStatusReserved:
		return commonpb.ReservationStatus_RESERVATION_STATUS_RESERVED
	case entity.ReservationStatusOrderCreating:
		return commonpb.ReservationStatus_RESERVATION_STATUS_ORDER_CREATING
	case entity.ReservationStatusOrderCreated:
		return commonpb.ReservationStatus_RESERVATION_STATUS_ORDER_CREATED
	case entity.ReservationStatusPaying:
		return commonpb.ReservationStatus_RESERVATION_STATUS_PAYING
	case entity.ReservationStatusPaid:
		return commonpb.ReservationStatus_RESERVATION_STATUS_PAID
	case entity.ReservationStatusConsumed:
		return commonpb.ReservationStatus_RESERVATION_STATUS_CONSUMED
	case entity.ReservationStatusReleased:
		return commonpb.ReservationStatus_RESERVATION_STATUS_RELEASED
	case entity.ReservationStatusExpired:
		return commonpb.ReservationStatus_RESERVATION_STATUS_EXPIRED
	case entity.ReservationStatusFailed:
		return commonpb.ReservationStatus_RESERVATION_STATUS_FAILED
	default:
		return commonpb.ReservationStatus_RESERVATION_STATUS_RESERVED
	}
}

func fromProtoReservationStatus(status commonpb.ReservationStatus) int32 {
	switch status {
	case commonpb.ReservationStatus_RESERVATION_STATUS_RESERVED:
		return entity.ReservationStatusReserved
	case commonpb.ReservationStatus_RESERVATION_STATUS_ORDER_CREATING:
		return entity.ReservationStatusOrderCreating
	case commonpb.ReservationStatus_RESERVATION_STATUS_ORDER_CREATED:
		return entity.ReservationStatusOrderCreated
	case commonpb.ReservationStatus_RESERVATION_STATUS_PAYING:
		return entity.ReservationStatusPaying
	case commonpb.ReservationStatus_RESERVATION_STATUS_PAID:
		return entity.ReservationStatusPaid
	case commonpb.ReservationStatus_RESERVATION_STATUS_CONSUMED:
		return entity.ReservationStatusConsumed
	case commonpb.ReservationStatus_RESERVATION_STATUS_RELEASED:
		return entity.ReservationStatusReleased
	case commonpb.ReservationStatus_RESERVATION_STATUS_EXPIRED:
		return entity.ReservationStatusExpired
	case commonpb.ReservationStatus_RESERVATION_STATUS_FAILED:
		return entity.ReservationStatusFailed
	default:
		return entity.ReservationStatusReserved
	}
}
