// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package server

import (
	"context"

	"seckill-mall/common/seckill"
	"seckill-mall/seckill-service/internal/logic"
	"seckill-mall/seckill-service/internal/svc"
)

type SeckillServiceServer struct {
	svcCtx *svc.ServiceContext
	seckill.UnimplementedSeckillServiceServer
}

func NewSeckillServiceServer(svcCtx *svc.ServiceContext) *SeckillServiceServer {
	return &SeckillServiceServer{
		svcCtx: svcCtx,
	}
}

// 秒杀下单（核心接口）
func (s *SeckillServiceServer) Seckill(ctx context.Context, in *seckill.SeckillRequest) (*seckill.SeckillResponse, error) {
	l := logic.NewSeckillLogic(ctx, s.svcCtx)
	return l.Seckill(in)
}

// 查询秒杀状态（轮询接口）
func (s *SeckillServiceServer) GetSeckillStatus(ctx context.Context, in *seckill.SeckillStatusRequest) (*seckill.SeckillStatusResponse, error) {
	l := logic.NewGetSeckillStatusLogic(ctx, s.svcCtx)
	return l.GetSeckillStatus(in)
}

// 查询秒杀结果
func (s *SeckillServiceServer) GetSeckillResult(ctx context.Context, in *seckill.SeckillResultRequest) (*seckill.SeckillResultResponse, error) {
	l := logic.NewGetSeckillResultLogic(ctx, s.svcCtx)
	return l.GetSeckillResult(in)
}

// 更新订单状态（Order-Service 内部调用，将 pending → success）
func (s *SeckillServiceServer) UpdateOrderStatus(ctx context.Context, in *seckill.UpdateOrderStatusRequest) (*seckill.UpdateOrderStatusResponse, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

// 超时失败补偿（Order-Service 内部调用）
func (s *SeckillServiceServer) CompensateFailedOrder(ctx context.Context, in *seckill.CompensateFailedOrderRequest) (*seckill.CompensateFailedOrderResponse, error) {
	l := logic.NewCompensateFailedOrderLogic(ctx, s.svcCtx)
	return l.CompensateFailedOrder(in)
}
