Name: product.rpc
ListenOn: 127.0.0.1:9082
Mode: dev
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: product.rpc

# 链路追踪
Telemetry:
  Name: product.rpc
  Endpoint: localhost:4317
  Sampler: 0.1
  Batcher: otlpgrpc

# Prometheus 指标暴露
Prometheus:
  Host: 0.0.0.0
  Port: 9182
  Path: /metrics

Redis:
  Host: localhost:6379
  Key: product.rpc.auth

MySQL:
  DataSource: root:Zz123456@tcp(localhost:3306)/seckill_mall?charset=utf8mb4&parseTime=True&loc=Local

SeckillRedis:
  Host: localhost:6379
