// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: proto/seckill.proto

package seckill

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeckillService_Seckill_FullMethodName               = "/seckill.SeckillService/Seckill"
	SeckillService_GetSeckillStatus_FullMethodName      = "/seckill.SeckillService/GetSeckillStatus"
	SeckillService_GetSeckillResult_FullMethodName      = "/seckill.SeckillService/GetSeckillResult"
	SeckillService_UpdateOrderStatus_FullMethodName     = "/seckill.SeckillService/UpdateOrderStatus"
	SeckillService_CompensateFailedOrder_FullMethodName = "/seckill.SeckillService/CompensateFailedOrder"
)

// SeckillServiceClient is the client API for SeckillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 秒杀服务（gRPC）
type SeckillServiceClient interface {
	// 秒杀下单（核心接口）
	Seckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error)
	// 查询秒杀状态（轮询接口）
	GetSeckillStatus(ctx context.Context, in *SeckillStatusRequest, opts ...grpc.CallOption) (*SeckillStatusResponse, error)
	// 查询秒杀结果
	GetSeckillResult(ctx context.Context, in *SeckillResultRequest, opts ...grpc.CallOption) (*SeckillResultResponse, error)
	// 更新订单状态（Order-Service 内部调用，将 pending → success）
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error)
	// 超时失败补偿（Order-Service 内部调用）
	CompensateFailedOrder(ctx context.Context, in *CompensateFailedOrderRequest, opts ...grpc.CallOption) (*CompensateFailedOrderResponse, error)
}

type seckillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillServiceClient(cc grpc.ClientConnInterface) SeckillServiceClient {
	return &seckillServiceClient{cc}
}

func (c *seckillServiceClient) Seckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillResponse)
	err := c.cc.Invoke(ctx, SeckillService_Seckill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) GetSeckillStatus(ctx context.Context, in *SeckillStatusRequest, opts ...grpc.CallOption) (*SeckillStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillStatusResponse)
	err := c.cc.Invoke(ctx, SeckillService_GetSeckillStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) GetSeckillResult(ctx context.Context, in *SeckillResultRequest, opts ...grpc.CallOption) (*SeckillResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeckillResultResponse)
	err := c.cc.Invoke(ctx, SeckillService_GetSeckillResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderStatusResponse)
	err := c.cc.Invoke(ctx, SeckillService_UpdateOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) CompensateFailedOrder(ctx context.Context, in *CompensateFailedOrderRequest, opts ...grpc.CallOption) (*CompensateFailedOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompensateFailedOrderResponse)
	err := c.cc.Invoke(ctx, SeckillService_CompensateFailedOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServiceServer is the server API for SeckillService service.
// All implementations must embed UnimplementedSeckillServiceServer
// for forward compatibility.
//
// 秒杀服务（gRPC）
type SeckillServiceServer interface {
	// 秒杀下单（核心接口）
	Seckill(context.Context, *SeckillRequest) (*SeckillResponse, error)
	// 查询秒杀状态（轮询接口）
	GetSeckillStatus(context.Context, *SeckillStatusRequest) (*SeckillStatusResponse, error)
	// 查询秒杀结果
	GetSeckillResult(context.Context, *SeckillResultRequest) (*SeckillResultResponse, error)
	// 更新订单状态（Order-Service 内部调用，将 pending → success）
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
	// 超时失败补偿（Order-Service 内部调用）
	CompensateFailedOrder(context.Context, *CompensateFailedOrderRequest) (*CompensateFailedOrderResponse, error)
	mustEmbedUnimplementedSeckillServiceServer()
}

// UnimplementedSeckillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeckillServiceServer struct{}

func (UnimplementedSeckillServiceServer) Seckill(context.Context, *SeckillRequest) (*SeckillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seckill not implemented")
}
func (UnimplementedSeckillServiceServer) GetSeckillStatus(context.Context, *SeckillStatusRequest) (*SeckillStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillStatus not implemented")
}
func (UnimplementedSeckillServiceServer) GetSeckillResult(context.Context, *SeckillResultRequest) (*SeckillResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeckillResult not implemented")
}
func (UnimplementedSeckillServiceServer) UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (UnimplementedSeckillServiceServer) CompensateFailedOrder(context.Context, *CompensateFailedOrderRequest) (*CompensateFailedOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompensateFailedOrder not implemented")
}
func (UnimplementedSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {}
func (UnimplementedSeckillServiceServer) testEmbeddedByValue()                        {}

// UnsafeSeckillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillServiceServer will
// result in compilation errors.
type UnsafeSeckillServiceServer interface {
	mustEmbedUnimplementedSeckillServiceServer()
}

func RegisterSeckillServiceServer(s grpc.ServiceRegistrar, srv SeckillServiceServer) {
	// If the following call panics, it indicates UnimplementedSeckillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeckillService_ServiceDesc, srv)
}

func _SeckillService_Seckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).Seckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_Seckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).Seckill(ctx, req.(*SeckillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetSeckillStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetSeckillStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_GetSeckillStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetSeckillStatus(ctx, req.(*SeckillStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetSeckillResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetSeckillResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_GetSeckillResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetSeckillResult(ctx, req.(*SeckillResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_UpdateOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_CompensateFailedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompensateFailedOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).CompensateFailedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillService_CompensateFailedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).CompensateFailedOrder(ctx, req.(*CompensateFailedOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeckillService_ServiceDesc is the grpc.ServiceDesc for SeckillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeckillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SeckillService",
	HandlerType: (*SeckillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seckill",
			Handler:    _SeckillService_Seckill_Handler,
		},
		{
			MethodName: "GetSeckillStatus",
			Handler:    _SeckillService_GetSeckillStatus_Handler,
		},
		{
			MethodName: "GetSeckillResult",
			Handler:    _SeckillService_GetSeckillResult_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _SeckillService_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "CompensateFailedOrder",
			Handler:    _SeckillService_CompensateFailedOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seckill.proto",
}
