// Code generated by MockGen. DO NOT EDIT.
// Source: ../common/seckill/seckill_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../common/seckill/seckill_grpc.pb.go -destination=internal/mock/mock_seckill.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	seckill "seckill-mall/common/seckill"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSeckillServiceClient is a mock of SeckillServiceClient interface.
type MockSeckillServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSeckillServiceClientMockRecorder
	isgomock struct{}
}

// MockSeckillServiceClientMockRecorder is the mock recorder for MockSeckillServiceClient.
type MockSeckillServiceClientMockRecorder struct {
	mock *MockSeckillServiceClient
}

// NewMockSeckillServiceClient creates a new mock instance.
func NewMockSeckillServiceClient(ctrl *gomock.Controller) *MockSeckillServiceClient {
	mock := &MockSeckillServiceClient{ctrl: ctrl}
	mock.recorder = &MockSeckillServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeckillServiceClient) EXPECT() *MockSeckillServiceClientMockRecorder {
	return m.recorder
}

// CompensateFailedOrder mocks base method.
func (m *MockSeckillServiceClient) CompensateFailedOrder(ctx context.Context, in *seckill.CompensateFailedOrderRequest, opts ...grpc.CallOption) (*seckill.CompensateFailedOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CompensateFailedOrder", varargs...)
	ret0, _ := ret[0].(*seckill.CompensateFailedOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompensateFailedOrder indicates an expected call of CompensateFailedOrder.
func (mr *MockSeckillServiceClientMockRecorder) CompensateFailedOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompensateFailedOrder", reflect.TypeOf((*MockSeckillServiceClient)(nil).CompensateFailedOrder), varargs...)
}

// GetSeckillResult mocks base method.
func (m *MockSeckillServiceClient) GetSeckillResult(ctx context.Context, in *seckill.SeckillResultRequest, opts ...grpc.CallOption) (*seckill.SeckillResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSeckillResult", varargs...)
	ret0, _ := ret[0].(*seckill.SeckillResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillResult indicates an expected call of GetSeckillResult.
func (mr *MockSeckillServiceClientMockRecorder) GetSeckillResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillResult", reflect.TypeOf((*MockSeckillServiceClient)(nil).GetSeckillResult), varargs...)
}

// GetSeckillStatus mocks base method.
func (m *MockSeckillServiceClient) GetSeckillStatus(ctx context.Context, in *seckill.SeckillStatusRequest, opts ...grpc.CallOption) (*seckill.SeckillStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSeckillStatus", varargs...)
	ret0, _ := ret[0].(*seckill.SeckillStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillStatus indicates an expected call of GetSeckillStatus.
func (mr *MockSeckillServiceClientMockRecorder) GetSeckillStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillStatus", reflect.TypeOf((*MockSeckillServiceClient)(nil).GetSeckillStatus), varargs...)
}

// Seckill mocks base method.
func (m *MockSeckillServiceClient) Seckill(ctx context.Context, in *seckill.SeckillRequest, opts ...grpc.CallOption) (*seckill.SeckillResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Seckill", varargs...)
	ret0, _ := ret[0].(*seckill.SeckillResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seckill indicates an expected call of Seckill.
func (mr *MockSeckillServiceClientMockRecorder) Seckill(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seckill", reflect.TypeOf((*MockSeckillServiceClient)(nil).Seckill), varargs...)
}

// UpdateOrderStatus mocks base method.
func (m *MockSeckillServiceClient) UpdateOrderStatus(ctx context.Context, in *seckill.UpdateOrderStatusRequest, opts ...grpc.CallOption) (*seckill.UpdateOrderStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrderStatus", varargs...)
	ret0, _ := ret[0].(*seckill.UpdateOrderStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockSeckillServiceClientMockRecorder) UpdateOrderStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockSeckillServiceClient)(nil).UpdateOrderStatus), varargs...)
}

// MockSeckillServiceServer is a mock of SeckillServiceServer interface.
type MockSeckillServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockSeckillServiceServerMockRecorder
	isgomock struct{}
}

// MockSeckillServiceServerMockRecorder is the mock recorder for MockSeckillServiceServer.
type MockSeckillServiceServerMockRecorder struct {
	mock *MockSeckillServiceServer
}

// NewMockSeckillServiceServer creates a new mock instance.
func NewMockSeckillServiceServer(ctrl *gomock.Controller) *MockSeckillServiceServer {
	mock := &MockSeckillServiceServer{ctrl: ctrl}
	mock.recorder = &MockSeckillServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeckillServiceServer) EXPECT() *MockSeckillServiceServerMockRecorder {
	return m.recorder
}

// CompensateFailedOrder mocks base method.
func (m *MockSeckillServiceServer) CompensateFailedOrder(arg0 context.Context, arg1 *seckill.CompensateFailedOrderRequest) (*seckill.CompensateFailedOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompensateFailedOrder", arg0, arg1)
	ret0, _ := ret[0].(*seckill.CompensateFailedOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompensateFailedOrder indicates an expected call of CompensateFailedOrder.
func (mr *MockSeckillServiceServerMockRecorder) CompensateFailedOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompensateFailedOrder", reflect.TypeOf((*MockSeckillServiceServer)(nil).CompensateFailedOrder), arg0, arg1)
}

// GetSeckillResult mocks base method.
func (m *MockSeckillServiceServer) GetSeckillResult(arg0 context.Context, arg1 *seckill.SeckillResultRequest) (*seckill.SeckillResultResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeckillResult", arg0, arg1)
	ret0, _ := ret[0].(*seckill.SeckillResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillResult indicates an expected call of GetSeckillResult.
func (mr *MockSeckillServiceServerMockRecorder) GetSeckillResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillResult", reflect.TypeOf((*MockSeckillServiceServer)(nil).GetSeckillResult), arg0, arg1)
}

// GetSeckillStatus mocks base method.
func (m *MockSeckillServiceServer) GetSeckillStatus(arg0 context.Context, arg1 *seckill.SeckillStatusRequest) (*seckill.SeckillStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeckillStatus", arg0, arg1)
	ret0, _ := ret[0].(*seckill.SeckillStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillStatus indicates an expected call of GetSeckillStatus.
func (mr *MockSeckillServiceServerMockRecorder) GetSeckillStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillStatus", reflect.TypeOf((*MockSeckillServiceServer)(nil).GetSeckillStatus), arg0, arg1)
}

// Seckill mocks base method.
func (m *MockSeckillServiceServer) Seckill(arg0 context.Context, arg1 *seckill.SeckillRequest) (*seckill.SeckillResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seckill", arg0, arg1)
	ret0, _ := ret[0].(*seckill.SeckillResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seckill indicates an expected call of Seckill.
func (mr *MockSeckillServiceServerMockRecorder) Seckill(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seckill", reflect.TypeOf((*MockSeckillServiceServer)(nil).Seckill), arg0, arg1)
}

// UpdateOrderStatus mocks base method.
func (m *MockSeckillServiceServer) UpdateOrderStatus(arg0 context.Context, arg1 *seckill.UpdateOrderStatusRequest) (*seckill.UpdateOrderStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", arg0, arg1)
	ret0, _ := ret[0].(*seckill.UpdateOrderStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockSeckillServiceServerMockRecorder) UpdateOrderStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockSeckillServiceServer)(nil).UpdateOrderStatus), arg0, arg1)
}

// mustEmbedUnimplementedSeckillServiceServer mocks base method.
func (m *MockSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSeckillServiceServer")
}

// mustEmbedUnimplementedSeckillServiceServer indicates an expected call of mustEmbedUnimplementedSeckillServiceServer.
func (mr *MockSeckillServiceServerMockRecorder) mustEmbedUnimplementedSeckillServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSeckillServiceServer", reflect.TypeOf((*MockSeckillServiceServer)(nil).mustEmbedUnimplementedSeckillServiceServer))
}

// MockUnsafeSeckillServiceServer is a mock of UnsafeSeckillServiceServer interface.
type MockUnsafeSeckillServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSeckillServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeSeckillServiceServerMockRecorder is the mock recorder for MockUnsafeSeckillServiceServer.
type MockUnsafeSeckillServiceServerMockRecorder struct {
	mock *MockUnsafeSeckillServiceServer
}

// NewMockUnsafeSeckillServiceServer creates a new mock instance.
func NewMockUnsafeSeckillServiceServer(ctrl *gomock.Controller) *MockUnsafeSeckillServiceServer {
	mock := &MockUnsafeSeckillServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSeckillServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSeckillServiceServer) EXPECT() *MockUnsafeSeckillServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSeckillServiceServer mocks base method.
func (m *MockUnsafeSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSeckillServiceServer")
}

// mustEmbedUnimplementedSeckillServiceServer indicates an expected call of mustEmbedUnimplementedSeckillServiceServer.
func (mr *MockUnsafeSeckillServiceServerMockRecorder) mustEmbedUnimplementedSeckillServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSeckillServiceServer", reflect.TypeOf((*MockUnsafeSeckillServiceServer)(nil).mustEmbedUnimplementedSeckillServiceServer))
}
