// Code generated by MockGen. DO NOT EDIT.
// Source: ../common/order/order_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../common/order/order_grpc.pb.go -destination=internal/mock/mock_order.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	common "seckill-mall/common/common"
	order "seckill-mall/common/order"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderServiceClient is a mock of OrderServiceClient interface.
type MockOrderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceClientMockRecorder
	isgomock struct{}
}

// MockOrderServiceClientMockRecorder is the mock recorder for MockOrderServiceClient.
type MockOrderServiceClientMockRecorder struct {
	mock *MockOrderServiceClient
}

// NewMockOrderServiceClient creates a new mock instance.
func NewMockOrderServiceClient(ctrl *gomock.Controller) *MockOrderServiceClient {
	mock := &MockOrderServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceClient) EXPECT() *MockOrderServiceClientMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderServiceClient) CancelOrder(ctx context.Context, in *order.CancelOrderRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelOrder", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderServiceClientMockRecorder) CancelOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).CancelOrder), varargs...)
}

// CreateNormalOrder mocks base method.
func (m *MockOrderServiceClient) CreateNormalOrder(ctx context.Context, in *order.CreateNormalOrderRequest, opts ...grpc.CallOption) (*order.OrderInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateNormalOrder", varargs...)
	ret0, _ := ret[0].(*order.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNormalOrder indicates an expected call of CreateNormalOrder.
func (mr *MockOrderServiceClientMockRecorder) CreateNormalOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNormalOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).CreateNormalOrder), varargs...)
}

// GetOrder mocks base method.
func (m *MockOrderServiceClient) GetOrder(ctx context.Context, in *order.GetOrderRequest, opts ...grpc.CallOption) (*order.OrderInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrder", varargs...)
	ret0, _ := ret[0].(*order.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderServiceClientMockRecorder) GetOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).GetOrder), varargs...)
}

// ListUserOrders mocks base method.
func (m *MockOrderServiceClient) ListUserOrders(ctx context.Context, in *order.ListUserOrdersRequest, opts ...grpc.CallOption) (*order.ListUserOrdersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListUserOrders", varargs...)
	ret0, _ := ret[0].(*order.ListUserOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserOrders indicates an expected call of ListUserOrders.
func (mr *MockOrderServiceClientMockRecorder) ListUserOrders(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserOrders", reflect.TypeOf((*MockOrderServiceClient)(nil).ListUserOrders), varargs...)
}

// PayOrder mocks base method.
func (m *MockOrderServiceClient) PayOrder(ctx context.Context, in *order.PayOrderRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PayOrder", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayOrder indicates an expected call of PayOrder.
func (mr *MockOrderServiceClientMockRecorder) PayOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).PayOrder), varargs...)
}

// RefundOrder mocks base method.
func (m *MockOrderServiceClient) RefundOrder(ctx context.Context, in *order.RefundOrderRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RefundOrder", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefundOrder indicates an expected call of RefundOrder.
func (mr *MockOrderServiceClientMockRecorder) RefundOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).RefundOrder), varargs...)
}

// MockOrderServiceServer is a mock of OrderServiceServer interface.
type MockOrderServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceServerMockRecorder
	isgomock struct{}
}

// MockOrderServiceServerMockRecorder is the mock recorder for MockOrderServiceServer.
type MockOrderServiceServerMockRecorder struct {
	mock *MockOrderServiceServer
}

// NewMockOrderServiceServer creates a new mock instance.
func NewMockOrderServiceServer(ctrl *gomock.Controller) *MockOrderServiceServer {
	mock := &MockOrderServiceServer{ctrl: ctrl}
	mock.recorder = &MockOrderServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceServer) EXPECT() *MockOrderServiceServerMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderServiceServer) CancelOrder(arg0 context.Context, arg1 *order.CancelOrderRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderServiceServerMockRecorder) CancelOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).CancelOrder), arg0, arg1)
}

// CreateNormalOrder mocks base method.
func (m *MockOrderServiceServer) CreateNormalOrder(arg0 context.Context, arg1 *order.CreateNormalOrderRequest) (*order.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNormalOrder", arg0, arg1)
	ret0, _ := ret[0].(*order.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNormalOrder indicates an expected call of CreateNormalOrder.
func (mr *MockOrderServiceServerMockRecorder) CreateNormalOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNormalOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).CreateNormalOrder), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockOrderServiceServer) GetOrder(arg0 context.Context, arg1 *order.GetOrderRequest) (*order.OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(*order.OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderServiceServerMockRecorder) GetOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).GetOrder), arg0, arg1)
}

// ListUserOrders mocks base method.
func (m *MockOrderServiceServer) ListUserOrders(arg0 context.Context, arg1 *order.ListUserOrdersRequest) (*order.ListUserOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserOrders", arg0, arg1)
	ret0, _ := ret[0].(*order.ListUserOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserOrders indicates an expected call of ListUserOrders.
func (mr *MockOrderServiceServerMockRecorder) ListUserOrders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserOrders", reflect.TypeOf((*MockOrderServiceServer)(nil).ListUserOrders), arg0, arg1)
}

// PayOrder mocks base method.
func (m *MockOrderServiceServer) PayOrder(arg0 context.Context, arg1 *order.PayOrderRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayOrder", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayOrder indicates an expected call of PayOrder.
func (mr *MockOrderServiceServerMockRecorder) PayOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).PayOrder), arg0, arg1)
}

// RefundOrder mocks base method.
func (m *MockOrderServiceServer) RefundOrder(arg0 context.Context, arg1 *order.RefundOrderRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundOrder", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefundOrder indicates an expected call of RefundOrder.
func (mr *MockOrderServiceServerMockRecorder) RefundOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).RefundOrder), arg0, arg1)
}

// mustEmbedUnimplementedOrderServiceServer mocks base method.
func (m *MockOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderServiceServer")
}

// mustEmbedUnimplementedOrderServiceServer indicates an expected call of mustEmbedUnimplementedOrderServiceServer.
func (mr *MockOrderServiceServerMockRecorder) mustEmbedUnimplementedOrderServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderServiceServer", reflect.TypeOf((*MockOrderServiceServer)(nil).mustEmbedUnimplementedOrderServiceServer))
}

// MockUnsafeOrderServiceServer is a mock of UnsafeOrderServiceServer interface.
type MockUnsafeOrderServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeOrderServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeOrderServiceServerMockRecorder is the mock recorder for MockUnsafeOrderServiceServer.
type MockUnsafeOrderServiceServerMockRecorder struct {
	mock *MockUnsafeOrderServiceServer
}

// NewMockUnsafeOrderServiceServer creates a new mock instance.
func NewMockUnsafeOrderServiceServer(ctrl *gomock.Controller) *MockUnsafeOrderServiceServer {
	mock := &MockUnsafeOrderServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeOrderServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeOrderServiceServer) EXPECT() *MockUnsafeOrderServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedOrderServiceServer mocks base method.
func (m *MockUnsafeOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderServiceServer")
}

// mustEmbedUnimplementedOrderServiceServer indicates an expected call of mustEmbedUnimplementedOrderServiceServer.
func (mr *MockUnsafeOrderServiceServerMockRecorder) mustEmbedUnimplementedOrderServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderServiceServer", reflect.TypeOf((*MockUnsafeOrderServiceServer)(nil).mustEmbedUnimplementedOrderServiceServer))
}
