// Code generated by MockGen. DO NOT EDIT.
// Source: ../common/product/product_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../common/product/product_grpc.pb.go -destination=internal/mock/mock_product.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	common "seckill-mall/common/common"
	product "seckill-mall/common/product"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockProductServiceClient is a mock of ProductServiceClient interface.
type MockProductServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceClientMockRecorder
	isgomock struct{}
}

// MockProductServiceClientMockRecorder is the mock recorder for MockProductServiceClient.
type MockProductServiceClientMockRecorder struct {
	mock *MockProductServiceClient
}

// NewMockProductServiceClient creates a new mock instance.
func NewMockProductServiceClient(ctrl *gomock.Controller) *MockProductServiceClient {
	mock := &MockProductServiceClient{ctrl: ctrl}
	mock.recorder = &MockProductServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceClient) EXPECT() *MockProductServiceClientMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductServiceClient) CreateProduct(ctx context.Context, in *product.CreateProductRequest, opts ...grpc.CallOption) (*product.ProductInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProduct", varargs...)
	ret0, _ := ret[0].(*product.ProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceClientMockRecorder) CreateProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductServiceClient)(nil).CreateProduct), varargs...)
}

// CreateSeckillProduct mocks base method.
func (m *MockProductServiceClient) CreateSeckillProduct(ctx context.Context, in *product.CreateSeckillProductRequest, opts ...grpc.CallOption) (*product.SeckillProductInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSeckillProduct", varargs...)
	ret0, _ := ret[0].(*product.SeckillProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeckillProduct indicates an expected call of CreateSeckillProduct.
func (mr *MockProductServiceClientMockRecorder) CreateSeckillProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeckillProduct", reflect.TypeOf((*MockProductServiceClient)(nil).CreateSeckillProduct), varargs...)
}

// DeductStock mocks base method.
func (m *MockProductServiceClient) DeductStock(ctx context.Context, in *product.DeductStockRequest, opts ...grpc.CallOption) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeductStock", varargs...)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductStock indicates an expected call of DeductStock.
func (mr *MockProductServiceClientMockRecorder) DeductStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductStock", reflect.TypeOf((*MockProductServiceClient)(nil).DeductStock), varargs...)
}

// DeleteProduct mocks base method.
func (m *MockProductServiceClient) DeleteProduct(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteProduct", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServiceClientMockRecorder) DeleteProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductServiceClient)(nil).DeleteProduct), varargs...)
}

// GetProduct mocks base method.
func (m *MockProductServiceClient) GetProduct(ctx context.Context, in *product.GetProductRequest, opts ...grpc.CallOption) (*product.ProductInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*product.ProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductServiceClientMockRecorder) GetProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductServiceClient)(nil).GetProduct), varargs...)
}

// GetSeckillProduct mocks base method.
func (m *MockProductServiceClient) GetSeckillProduct(ctx context.Context, in *product.GetSeckillProductRequest, opts ...grpc.CallOption) (*product.SeckillProductInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSeckillProduct", varargs...)
	ret0, _ := ret[0].(*product.SeckillProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillProduct indicates an expected call of GetSeckillProduct.
func (mr *MockProductServiceClientMockRecorder) GetSeckillProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillProduct", reflect.TypeOf((*MockProductServiceClient)(nil).GetSeckillProduct), varargs...)
}

// GetStock mocks base method.
func (m *MockProductServiceClient) GetStock(ctx context.Context, in *common.IdRequest, opts ...grpc.CallOption) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStock", varargs...)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockProductServiceClientMockRecorder) GetStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockProductServiceClient)(nil).GetStock), varargs...)
}

// ListActiveSeckillProducts mocks base method.
func (m *MockProductServiceClient) ListActiveSeckillProducts(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[product.SeckillProductInfo], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListActiveSeckillProducts", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[product.SeckillProductInfo])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveSeckillProducts indicates an expected call of ListActiveSeckillProducts.
func (mr *MockProductServiceClientMockRecorder) ListActiveSeckillProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSeckillProducts", reflect.TypeOf((*MockProductServiceClient)(nil).ListActiveSeckillProducts), varargs...)
}

// ListProducts mocks base method.
func (m *MockProductServiceClient) ListProducts(ctx context.Context, in *product.ListProductsRequest, opts ...grpc.CallOption) (*product.ListProductsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProducts", varargs...)
	ret0, _ := ret[0].(*product.ListProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductServiceClientMockRecorder) ListProducts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductServiceClient)(nil).ListProducts), varargs...)
}

// RollbackStock mocks base method.
func (m *MockProductServiceClient) RollbackStock(ctx context.Context, in *product.RollbackStockRequest, opts ...grpc.CallOption) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RollbackStock", varargs...)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackStock indicates an expected call of RollbackStock.
func (mr *MockProductServiceClientMockRecorder) RollbackStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackStock", reflect.TypeOf((*MockProductServiceClient)(nil).RollbackStock), varargs...)
}

// UpdateProduct mocks base method.
func (m *MockProductServiceClient) UpdateProduct(ctx context.Context, in *product.UpdateProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProduct", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceClientMockRecorder) UpdateProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductServiceClient)(nil).UpdateProduct), varargs...)
}

// UpdateSeckillProduct mocks base method.
func (m *MockProductServiceClient) UpdateSeckillProduct(ctx context.Context, in *product.UpdateSeckillProductRequest, opts ...grpc.CallOption) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSeckillProduct", varargs...)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSeckillProduct indicates an expected call of UpdateSeckillProduct.
func (mr *MockProductServiceClientMockRecorder) UpdateSeckillProduct(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeckillProduct", reflect.TypeOf((*MockProductServiceClient)(nil).UpdateSeckillProduct), varargs...)
}

// MockProductServiceServer is a mock of ProductServiceServer interface.
type MockProductServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceServerMockRecorder
	isgomock struct{}
}

// MockProductServiceServerMockRecorder is the mock recorder for MockProductServiceServer.
type MockProductServiceServerMockRecorder struct {
	mock *MockProductServiceServer
}

// NewMockProductServiceServer creates a new mock instance.
func NewMockProductServiceServer(ctrl *gomock.Controller) *MockProductServiceServer {
	mock := &MockProductServiceServer{ctrl: ctrl}
	mock.recorder = &MockProductServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceServer) EXPECT() *MockProductServiceServerMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductServiceServer) CreateProduct(arg0 context.Context, arg1 *product.CreateProductRequest) (*product.ProductInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(*product.ProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceServerMockRecorder) CreateProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductServiceServer)(nil).CreateProduct), arg0, arg1)
}

// CreateSeckillProduct mocks base method.
func (m *MockProductServiceServer) CreateSeckillProduct(arg0 context.Context, arg1 *product.CreateSeckillProductRequest) (*product.SeckillProductInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeckillProduct", arg0, arg1)
	ret0, _ := ret[0].(*product.SeckillProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeckillProduct indicates an expected call of CreateSeckillProduct.
func (mr *MockProductServiceServerMockRecorder) CreateSeckillProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeckillProduct", reflect.TypeOf((*MockProductServiceServer)(nil).CreateSeckillProduct), arg0, arg1)
}

// DeductStock mocks base method.
func (m *MockProductServiceServer) DeductStock(arg0 context.Context, arg1 *product.DeductStockRequest) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductStock", arg0, arg1)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeductStock indicates an expected call of DeductStock.
func (mr *MockProductServiceServerMockRecorder) DeductStock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductStock", reflect.TypeOf((*MockProductServiceServer)(nil).DeductStock), arg0, arg1)
}

// DeleteProduct mocks base method.
func (m *MockProductServiceServer) DeleteProduct(arg0 context.Context, arg1 *common.IdRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServiceServerMockRecorder) DeleteProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductServiceServer)(nil).DeleteProduct), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockProductServiceServer) GetProduct(arg0 context.Context, arg1 *product.GetProductRequest) (*product.ProductInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(*product.ProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductServiceServerMockRecorder) GetProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductServiceServer)(nil).GetProduct), arg0, arg1)
}

// GetSeckillProduct mocks base method.
func (m *MockProductServiceServer) GetSeckillProduct(arg0 context.Context, arg1 *product.GetSeckillProductRequest) (*product.SeckillProductInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeckillProduct", arg0, arg1)
	ret0, _ := ret[0].(*product.SeckillProductInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeckillProduct indicates an expected call of GetSeckillProduct.
func (mr *MockProductServiceServerMockRecorder) GetSeckillProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeckillProduct", reflect.TypeOf((*MockProductServiceServer)(nil).GetSeckillProduct), arg0, arg1)
}

// GetStock mocks base method.
func (m *MockProductServiceServer) GetStock(arg0 context.Context, arg1 *common.IdRequest) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStock", arg0, arg1)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStock indicates an expected call of GetStock.
func (mr *MockProductServiceServerMockRecorder) GetStock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStock", reflect.TypeOf((*MockProductServiceServer)(nil).GetStock), arg0, arg1)
}

// ListActiveSeckillProducts mocks base method.
func (m *MockProductServiceServer) ListActiveSeckillProducts(arg0 *common.Empty, arg1 grpc.ServerStreamingServer[product.SeckillProductInfo]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveSeckillProducts", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListActiveSeckillProducts indicates an expected call of ListActiveSeckillProducts.
func (mr *MockProductServiceServerMockRecorder) ListActiveSeckillProducts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveSeckillProducts", reflect.TypeOf((*MockProductServiceServer)(nil).ListActiveSeckillProducts), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockProductServiceServer) ListProducts(arg0 context.Context, arg1 *product.ListProductsRequest) (*product.ListProductsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].(*product.ListProductsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductServiceServerMockRecorder) ListProducts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductServiceServer)(nil).ListProducts), arg0, arg1)
}

// RollbackStock mocks base method.
func (m *MockProductServiceServer) RollbackStock(arg0 context.Context, arg1 *product.RollbackStockRequest) (*product.StockOperationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackStock", arg0, arg1)
	ret0, _ := ret[0].(*product.StockOperationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackStock indicates an expected call of RollbackStock.
func (mr *MockProductServiceServerMockRecorder) RollbackStock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackStock", reflect.TypeOf((*MockProductServiceServer)(nil).RollbackStock), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockProductServiceServer) UpdateProduct(arg0 context.Context, arg1 *product.UpdateProductRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceServerMockRecorder) UpdateProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductServiceServer)(nil).UpdateProduct), arg0, arg1)
}

// UpdateSeckillProduct mocks base method.
func (m *MockProductServiceServer) UpdateSeckillProduct(arg0 context.Context, arg1 *product.UpdateSeckillProductRequest) (*common.BoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeckillProduct", arg0, arg1)
	ret0, _ := ret[0].(*common.BoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSeckillProduct indicates an expected call of UpdateSeckillProduct.
func (mr *MockProductServiceServerMockRecorder) UpdateSeckillProduct(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeckillProduct", reflect.TypeOf((*MockProductServiceServer)(nil).UpdateSeckillProduct), arg0, arg1)
}

// mustEmbedUnimplementedProductServiceServer mocks base method.
func (m *MockProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProductServiceServer")
}

// mustEmbedUnimplementedProductServiceServer indicates an expected call of mustEmbedUnimplementedProductServiceServer.
func (mr *MockProductServiceServerMockRecorder) mustEmbedUnimplementedProductServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProductServiceServer", reflect.TypeOf((*MockProductServiceServer)(nil).mustEmbedUnimplementedProductServiceServer))
}

// MockUnsafeProductServiceServer is a mock of UnsafeProductServiceServer interface.
type MockUnsafeProductServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeProductServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeProductServiceServerMockRecorder is the mock recorder for MockUnsafeProductServiceServer.
type MockUnsafeProductServiceServerMockRecorder struct {
	mock *MockUnsafeProductServiceServer
}

// NewMockUnsafeProductServiceServer creates a new mock instance.
func NewMockUnsafeProductServiceServer(ctrl *gomock.Controller) *MockUnsafeProductServiceServer {
	mock := &MockUnsafeProductServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeProductServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeProductServiceServer) EXPECT() *MockUnsafeProductServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedProductServiceServer mocks base method.
func (m *MockUnsafeProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProductServiceServer")
}

// mustEmbedUnimplementedProductServiceServer indicates an expected call of mustEmbedUnimplementedProductServiceServer.
func (mr *MockUnsafeProductServiceServerMockRecorder) mustEmbedUnimplementedProductServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProductServiceServer", reflect.TypeOf((*MockUnsafeProductServiceServer)(nil).mustEmbedUnimplementedProductServiceServer))
}
