// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"
	commonpb "seckill-mall/common/common"

	"seckill-mall/common/order"
	"seckill-mall/order-service/internal/logic"
	"seckill-mall/order-service/internal/svc"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// ============ gRPC 接口 ============
func (s *OrderServiceServer) CreateNormalOrder(ctx context.Context, in *order.CreateNormalOrderRequest) (*order.OrderInfo, error) {
	l := logic.NewCreateNormalOrderLogic(ctx, s.svcCtx)
	return l.CreateNormalOrder(in)
}

// 获取订单详情
func (s *OrderServiceServer) GetOrder(ctx context.Context, in *order.GetOrderRequest) (*order.OrderInfo, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// 用户订单列表
func (s *OrderServiceServer) ListUserOrders(ctx context.Context, in *order.ListUserOrdersRequest) (*order.ListUserOrdersResponse, error) {
	l := logic.NewListUserOrdersLogic(ctx, s.svcCtx)
	return l.ListUserOrders(in)
}

// 取消订单
func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *order.CancelOrderRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// 支付订单
func (s *OrderServiceServer) PayOrder(ctx context.Context, in *order.PayOrderRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewPayOrderLogic(ctx, s.svcCtx)
	return l.PayOrder(in)
}

// 创建支付单
func (s *OrderServiceServer) CreatePayment(ctx context.Context, in *order.CreatePaymentRequest) (*order.CreatePaymentResponse, error) {
	return &order.CreatePaymentResponse{
		Success: true,
		Message: "支付单接口已预留，后续在 Phase D 落地支付子域",
		Payment: &order.PaymentInfo{
			OrderId:   in.OrderId,
			Channel:   in.Channel,
			RequestId: in.RequestId,
			Status:    commonpb.PaymentStatus_PAYMENT_STATUS_INIT,
		},
	}, nil
}

// 查询支付单
func (s *OrderServiceServer) GetPayment(ctx context.Context, in *order.GetPaymentRequest) (*order.PaymentInfo, error) {
	return &order.PaymentInfo{
		PaymentId: in.PaymentId,
		OrderId:   in.OrderId,
		Status:    commonpb.PaymentStatus_PAYMENT_STATUS_INIT,
	}, nil
}

// 处理支付回调
func (s *OrderServiceServer) HandlePaymentCallback(ctx context.Context, in *order.HandlePaymentCallbackRequest) (*commonpb.BoolResponse, error) {
	return &commonpb.BoolResponse{
		Success: true,
		Message: "支付回调接口已预留，后续在 Phase D 落地支付审计链路",
	}, nil
}

// 退款
func (s *OrderServiceServer) RefundOrder(ctx context.Context, in *order.RefundOrderRequest) (*commonpb.BoolResponse, error) {
	l := logic.NewRefundOrderLogic(ctx, s.svcCtx)
	return l.RefundOrder(in)
}
